apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eddis.labs.ai
spec:
  group: labs.ai
  names:
    kind: Eddi
    listKind: EddiList
    plural: eddis
    singular: eddi
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
