---
- name: Setup mongo-db
  when: no_mongo_setup_enable |bool
  include_tasks: 01-mongo_db-deployment.yml
  tags:
  - db
  - eddi

- name:  setup eddi 
  include_tasks: 02-eddi-deployment.yml
  tags:
  - eddi
